# Generated by Django 3.0.5 on 2020-05-08 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='blogpost',
            field=models.ForeignKey(default=32, on_delete=django.db.models.deletion.CASCADE, to='blog.BlogPost'),
            preserve_default=False,
        ),
    ]
